Voetbal\Sport\PlanningConfig:
  type: entity
  repositoryClass: Voetbal\Sport\PlanningConfig\Repository
  table: sportplanningconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    minNrOfGames:
      type: smallint
      nullable: false
      unique: false
    iddep: # DEPRECATED
      type: integer
      nullable: true
      unique: false
  manyToOne:
    roundNumber:
      targetEntity: Voetbal\Round\Number
      inversedBy: sportPlanningConfigs
      joinColumn:
        name: roundnumberid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    sport:
      targetEntity: Voetbal\Sport
      joinColumn:
        name: sportid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
  uniqueConstraints:
    number_u_idx:
      columns: [ roundnumberid, sportid ]