Voetbal\Sport\Config:
  type: entity
  repositoryClass: Voetbal\Sport\Config\Repository
  table: sportconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    winPoints:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    drawPoints:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    winPointsExt:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    drawPointsExt:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    pointsCalculation:
      type: smallint
      nullable: true
      unique: false
    nrOfGameCompetitors:
      type: integer
      unique: false
      nullable: false
  oneToOne:
    score:
      targetEntity: Voetbal\Sport\Config\Score
      joinColumn:
        name: scoreid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
      cascade: [ persist, remove ]
  manyToOne:
    supplier:
      targetEntity: Voetbal\Round\Number
      inversedBy: sportConfigs
      joinColumn:
        name: roundnumberid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    sport:
      targetEntity: Voetbal\Sport
      joinColumn:
        name: sportid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE