Voetbal\Round\Config:
  type: entity
  repositoryClass: Voetbal\Round\Config\Repository
  table: roundconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    qualifyRule:
      type: smallint
      nullable: false
      default: !php/const:Voetbal\QualifyRule::SOCCERWORLDCUP
      unique: false
    nrOfHeadtoheadMatches:
      type: smallint
      nullable: false
      unique: false
    winPoints:
      type: smallint
      nullable: false
      unique: false
    drawPoints:
      type: smallint
      nullable: false
      unique: false
    hasExtension:
      type: boolean
      nullable: false
      unique: false
    winPointsExt:
      type: smallint
      nullable: false
      unique: false
    drawPointsExt:
      type: smallint
      nullable: false
      unique: false
    minutesPerGameExt:
      type: smallint
      nullable: false
      unique: false
    enableTime:
      type: boolean
      nullable: false
      unique: false
    minutesPerGame:
      type: smallint
      nullable: false
      unique: false
    minutesInBetween:
      type: smallint
      nullable: true
      unique: false
  oneToMany:
    scores:
      targetEntity: Voetbal\Round\Config\Score
      mappedBy: config
      cascade: [ remove ]
  oneToOne:
    round:
      targetEntity: Voetbal\Round
      inversedBy: config
      joinColumn:
        name: roundid
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
  uniqueConstraints:
    number_u_idx:
      columns: [ roundid ]