Voetbal\Round\Config\Score:
  type: entity
  # update roundscoreconfigs set roundconfigid = (select id from roundconfigs where roundid = roundscoreconfigs.roundid )
  repositoryClass: Voetbal\Round\Config\Score\Repository
  table: roundscoreconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
      length: !php/const Voetbal\Round\Config\Score\Options::MAX_LENGTH_NAME
      unique: false
    direction:
      type: smallint
      nullable: false
      unique: false
    maximum:
      type: smallint
      nullable: false
      unique: false
  manyToOne:
    config:
      targetEntity: Voetbal\Round\Config
      inversedBy: scores
      joinColumn:
        name: roundconfigid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
  oneToOne:
    parent:
      targetEntity: Voetbal\Round\Config\Score
      inversedBy: child
      joinColumn:
        name: parentid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    child:
      targetEntity: Voetbal\Round\Config\Score
      mappedBy: parent
      cascade: [ persist, remove ]
  uniqueConstraints:
    number_u_idx:
      columns: [ parentid ]