Voetbal\Sport\Config\Score:
  type: entity
  repositoryClass: Voetbal\Sport\Config\Score\Repository
  table: sportconfigscores
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    direction:
      type: smallint
      nullable: false
      unique: false
    maximum:
      type: smallint
      nullable: false
      unique: false
    iddep:
      type: integer
      nullable: true
      unique: false
    roundconfigiddep:
      type: integer
      nullable: true
      unique: false
  oneToOne:
    parent:
      targetEntity: Voetbal\Sport\Config\Score
      inversedBy: child
      joinColumn:
        name: parentid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    child:
      targetEntity: Voetbal\Sport\Config\Score
      mappedBy: parent
      cascade: [ persist, remove ]
  uniqueConstraints:
    number_u_idx:
      columns: [ parentid ]