Voetbal\Planning\Config:
  type: entity
  repositoryClass: Voetbal\Planning\Config\Repository
  table: planningconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    hasExtensionDep:
      type: boolean
      nullable: false
      unique: false
      column: hasExtension
    minutesPerGameExt:
      type: smallint
      nullable: false
      unique: false
    enableTime:
      type: boolean
      nullable: false
      unique: false
    minutesPerGame:
      type: smallint
      nullable: false
      unique: false
    minutesAfter:
      type: smallint
      nullable: true
      unique: false
      column: minutesInBetween
    minutesBetweenGames:
      type: smallint
      nullable: true
      unique: false
    teamup:
      type: boolean
      nullable: true
      unique: false
    selfReferee:
      type: boolean
      nullable: true
      unique: false
    nrOfHeadtohead:
      type: smallint
      nullable: false
      unique: false
    rniddep: # DEPRECATED
      type: integer
      nullable: true
      unique: false