Voetbal\Config\Count\Score:
  type: entity
  repositoryClass: Voetbal\Config\Count\Score\Repository
  table: countscoreconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
      length: !php/const Voetbal\Config\Count\Score::MAX_LENGTH_NAME
      unique: false
    direction:
      type: smallint
      nullable: false
      unique: false
    maximum:
      type: smallint
      nullable: false
      unique: false
    iddep:
      type: integer
      nullable: false
      unique: false
    roundconfigiddep:
      type: integer
      nullable: false
      unique: false
  oneToOne:
    parent:
      targetEntity: Voetbal\Config\Count\Score
      inversedBy: child
      joinColumn:
        name: parentid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    child:
      targetEntity: Voetbal\Config\Count\Score
      mappedBy: parent
      cascade: [ persist, remove ]
  uniqueConstraints:
    number_u_idx:
      columns: [ parentid ]