Voetbal\Config:
  type: entity
  repositoryClass: Voetbal\Config\Repository
  table: roundconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    qualifyRule:
      type: smallint
      nullable: false
      default: !php/const Voetbal\Ranking\Service::RULESSET_WC
      unique: false
    nrOfHeadtoheadMatches:
      type: smallint
      nullable: false
      unique: false
    winPoints:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    drawPoints:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    hasExtension:
      type: boolean
      nullable: false
      unique: false
    winPointsExt:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    drawPointsExt:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    minutesPerGameExt:
      type: smallint
      nullable: false
      unique: false
    enableTime:
      type: boolean
      nullable: false
      unique: false
    minutesPerGame:
      type: smallint
      nullable: false
      unique: false
    minutesAfter:
      type: smallint
      nullable: true
      unique: false
      column: minutesInBetween
    minutesBetweenGames:
      type: smallint
      nullable: true
      unique: false
    teamup:
      type: boolean
      nullable: true
      unique: false
    pointsCalculation:
      type: smallint
      nullable: true
      unique: false
    selfReferee:
      type: boolean
      nullable: true
      unique: false
  oneToOne:
    score:
      targetEntity: Voetbal\Config\Score
      joinColumn:
        name: scoreid
        referencedColumnName: id
        nullable: true # should be false
        onDelete: CASCADE
      cascade: [ persist, remove ]
  oneToMany:
    scoresDep:
      targetEntity: Voetbal\Config\Score
      mappedBy: configDep
      cascade: [ persist, remove ]