Voetbal\Round\ScoreConfig:
  type: entity
  repositoryClass: Voetbal\Round\ScoreConfig\Repository
  table: roundscoreconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
      length: !php/const:Voetbal\Round\ScoreConfig::MAX_LENGTH_NAME
      unique: false
    direction:
      type: smallint
      nullable: false
      unique: false
    maximum:
      type: smallint
      nullable: false
      unique: false
  manyToOne:
    round:
      targetEntity: Voetbal\Round
      inversedBy: scoreConfigs
      joinColumn:
        name: roundid
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
  oneToOne:
    parent:
      targetEntity: Voetbal\Round\ScoreConfig
      inversedBy: child
      joinColumn:
        name: parentid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    child:
      targetEntity: Voetbal\Round\ScoreConfig
      mappedBy: parent
      cascade: [ persist, remove ]
  uniqueConstraints:
    number_u_idx:
      columns: [ parentid ]