Voetbal\Sport\Config:
  type: entity
  repositoryClass: Voetbal\Sport\Config\Repository
  table: sportconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    winPoints:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    drawPoints:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    winPointsExt:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    drawPointsExt:
      type: decimal
      precision: 3
      scale: 1
      nullable: false
      unique: false
    pointsCalculation:
      type: smallint
      nullable: true
      unique: false
    nrOfGamePlaces:
      type: integer
      unique: false
      nullable: false
  manyToOne:
    competition:
      targetEntity: Voetbal\Competition
      inversedBy: sportConfigs
      joinColumn:
        name: competitionid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    sport:
      targetEntity: Voetbal\Sport
      joinColumn:
        name: sportid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE