Voetbal\Round\ScoreConfig:
  type: entity
  repositoryClass: Voetbal\Round\ScoreConfig\Repository
  table: roundscoreconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
      length: !php/const:Voetbal\Round\ScoreConfig::MAX_LENGTH_NAME
      unique: false
    start:
      type: smallint
      nullable: false
      unique: false
    goal:
      type: smallint
      nullable: false
      unique: false
  oneToOne:
    round:
      targetEntity: Voetbal\Round
      inversedBy: scoreConfig
      joinColumn:
        name: roundid
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
    parent:
      targetEntity: Voetbal\Round\ScoreConfig
#      inversedBy: child
      joinColumn:
        name: parentid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
      cascade: [ persist, remove ]
#    child:
#      targetEntity: Voetbal\Round\ScoreConfig
#      mappedBy: parent
#      cascade: [ persist, remove ]
  uniqueConstraints:
    number_u_idx:
      columns: [ parentid ]