Voetbal\Config\Dep\Score:
  type: entity
  repositoryClass: Voetbal\Config\Dep\Score\Repository
  table: roundscoreconfigs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
      length: !php/const Voetbal\Sport::MAX_LENGTH_UNITNAME
      unique: false
    direction:
      type: smallint
      nullable: false
      unique: false
    maximum:
      type: smallint
      nullable: false
      unique: false
  manyToOne:
    configDep:
      targetEntity: Voetbal\Config\Dep
      inversedBy: scoresDep
      joinColumn:
        name: roundconfigid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
  oneToOne:
    parent:
      targetEntity: Voetbal\Config\Dep\Score
      inversedBy: child
      joinColumn:
        name: parentid
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    child:
      targetEntity: Voetbal\Config\Dep\Score
      mappedBy: parent
      cascade: [ persist, remove ]
  uniqueConstraints:
    number_u_idx:
      columns: [ parentid ]