Voetbal\Config:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    qualifyRule:
      type: integer
    nrOfHeadtoheadMatches:
      type: integer
    winPoints:
      type: float
    drawPoints:
      type: float
    hasExtension:
      type: bool
    winPointsExt:
      type: float
    drawPointsExt:
      type: float
    minutesPerGameExt:
      type: integer
    minutesPerGame:
      type: integer
    enableTime:
      type: bool
    minutesBetweenGames:
      type: integer
    minutesAfter:
      type: integer
    score:
      type: Voetbal\Config\Score
    teamup:
      type: bool
    pointsCalculation:
      type: integer
    selfReferee:
      type: bool

