Voetbal\Planning\Config:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    hasExtension:
      type: bool
    minutesPerGameExt:
      type: integer
    minutesPerGame:
      type: integer
    enableTime:
      type: bool
    minutesBetweenGames:
      type: integer
    minutesAfter:
      type: integer
    teamup:
      type: bool
    selfReferee:
      type: bool