Voetbal\Planning\Config:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    minutesPerGameExt:
      type: integer
    minutesPerGame:
      type: integer
    enableTime:
      type: boolean
    minutesBetweenGames:
      type: integer
    minutesAfter:
      type: integer
    teamup:
      type: boolean
    selfReferee:
      type: boolean
    nrOfHeadtohead:
      type: integer
