Voetbal\Round\Config:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    qualifyRule:
      type: integer
    nrOfHeadtoheadMatches:
      type: integer
    winPoints:
      type: integer
    drawPoints:
      type: integer
    hasExtension:
      type: boolean
    winPointsExt:
      type: integer
    drawPointsExt:
      type: integer
    minutesPerGameExt:
      type: integer
    minutesPerGame:
      type: integer
    enableTime:
      type: boolean
    minutesBetweenGames:
      type: integer
    minutesAfter:
      type: integer
    score:
      type: Voetbal\Round\Config\Score