Voetbal\Sport\Config:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    winPoints:
      type: float
    drawPoints:
      type: float
    winPointsExt:
      type: float
    drawPointsExt:
      type: float
    score:
      type: Voetbal\Sport\Config\Score
    pointsCalculation:
      type: integer
    nrOfGameCompetitors:
      type: int
  virtual_properties:
    getSportId:
      type: integer
      serialized_name: sportId