Voetbal\Sport\CountConfig:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    qualifyRule:
      type: integer
    winPoints:
      type: float
    drawPoints:
      type: float
    winPointsExt:
      type: float
    drawPointsExt:
      type: float
    score:
      type: Voetbal\Sport\CountConfig\Score
    pointsCalculation:
      type: integer
    sportId:
      type: integer
      read_only: true