Voetbal\Sport\PlanningConfig:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    nrOfHeadtoheadMatches:
      type: integer
  virtual_properties:
    getSportId:
      type: integer
      serialized_name: sportId