# config/db.yaml
Season:
  type: entity
  table: seasons
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  embedded:
    seasonname:
      class: SeasonName
      columnPrefix: false

SeasonName:
  type: embeddable
  table: seasons
  columnPrefix: false
  fields:
    name: { type: string }