<?php

namespace Voetbal\Season;

/**
 * Season
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Repository extends \Voetbal\Repository
{

}
