<?php

namespace Voetbal\Season;

use Voetbal\External\Importable\Repository as ImportableRepository;

/**
 * Season
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Repository extends \Voetbal\Repository implements ImportableRepository
{

}
