<?php

namespace Voetbal\Repository;

use Voetbal\Repository\Main;

/**
 * Association
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Association extends Main
{

}
