<?php

namespace Voetbal\Repository;

/**
 * Competitionseason
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Competitionseason extends Main
{

}
